name: Daily Investment Edge Digest

on:
  schedule:
    - cron: '0 13 * * *'  # 8am CT (1pm UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-and-send:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check watchlist exists
      run: |
        if [ ! -f watchlist.json ]; then
          echo "Error: watchlist.json not found"
          exit 1
        fi
        echo "Watchlist loaded successfully"
    
    - name: Generate digest
      env:
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        MARKETAUX_API_KEY: ${{ secrets.MARKETAUX_API_KEY }}
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      run: |
        python src/nextgen_digest.py
        echo "Digest generated successfully"
    
    - name: Render email
      run: |
        python src/render_email.py
        echo "Email rendered successfully"
    
    - name: Send email
      env:
        GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        python src/send_email.py
        echo "Email sent successfully"
    
    - name: Upload artifacts (for debugging)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: digest-artifacts
        path: |
          digest.json
          daily_digest.json
          email_output.html
        retention-days: 7
