name: Daily Investment Edge Digest

on:
  schedule:
    - cron: '0 13 * * *'  # 8am CT (1pm UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-and-send:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check watchlist exists
      run: |
        if [ -f "data/watchlist.json" ]; then
          echo "✓ Found data/watchlist.json"
          cp data/watchlist.json watchlist.json
        elif [ -f "data/companies.json" ]; then
          echo "✓ Found data/companies.json (using as fallback)"
          cp data/companies.json watchlist.json
        else
          echo "⚠ Warning: No watchlist found"
        fi
    
    - name: Generate and send Investment Edge digest
      env:
        # API Keys for data fetching
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        MARKETAUX_API_KEY: ${{ secrets.MARKETAUX_API_KEY }}
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        
        # Email configuration - YOUR ACTUAL SECRET NAMES
        SENDER_EMAIL: ${{ secrets.GMAIL_ADDRESS }}
        SENDER_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAIL }}
        SENDER_NAME: "Investment Edge"
        
        # Enable NextGen digest
        NEXTGEN_DIGEST: "true"
      run: |
        echo "Starting Investment Edge digest generation..."
        # This is the ONLY file that needs to run - it handles everything!
        python src/ci_entrypoint.py
        echo "Investment Edge digest sent successfully!"
    
    - name: Upload artifacts (for debugging)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: digest-artifacts-${{ github.run_number }}
        path: |
          *.json
          *.html
          logs/
        retention-days: 7
        if-no-files-found: ignore
